const state={token:localStorage.getItem('ramify.token')||'',envs:[],selected:null,baseDomain:'',logsTimer:null,refreshTimer:null};
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function api(path,options={}){options.headers={...(options.headers||{}),...(state.token?{Authorization:`Bearer ${state.token}`}:{})};return fetch(path,options).then(async r=>{if(r.status===401){openToken();throw Error('Unauthorized')}if(!r.ok)throw Error((await r.text())||`Request failed (${r.status})`);return r});}
function openToken(){const d=$('token-dialog');$('token').value=state.token;d.showModal()}
function toast(message){const t=$('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)}
function statusClass(s){return String(s||'').toLowerCase().replace(/[^a-z]/g,'')}
function relativeTime(value){if(!value)return '—';const d=new Date(value),m=Math.round((Date.now()-d)/60000);if(m<1)return 'just now';if(m<60)return `${m}m ago`;const h=Math.round(m/60);if(h<48)return `${h}h ago`;return `${Math.round(h/24)}d ago`}
function expiry(value){if(!value)return 'No expiry';const d=new Date(value),m=Math.round((d-Date.now())/60000);if(m<0)return 'expired';if(m<60)return `${m}m left`;if(m<1440)return `${Math.round(m/60)}h left`;return `${Math.round(m/1440)}d left`}
async function load(){try{const r=await api('/environments/?limit=100');state.envs=await r.json();$('connection').className='connection online';$('connection').textContent='Live';renderList();renderStats();if(state.selected){const found=state.envs.find(e=>e.ID===state.selected.ID);if(found){state.selected=found;renderDetail()}}$('updated').textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});}catch(e){$('connection').className='connection offline';$('connection').textContent='Disconnected';if(e.message!=='Unauthorized')toast(e.message)}}
function renderStats(){$('total').textContent=state.envs.length;$('ready').textContent=state.envs.filter(e=>['ready','running'].includes(String(e.Status).toLowerCase())).length;$('attention').textContent=state.envs.filter(e=>['failed','destroying','expired'].includes(String(e.Status).toLowerCase())).length}
function renderList(){const q=$('filter').value.toLowerCase();const list=state.envs.filter(e=>`${e.Project} ${e.Branch} ${e.Status}`.toLowerCase().includes(q));$('environment-list').innerHTML=list.length?list.map(e=>`<div class="environment ${state.selected?.ID===e.ID?'selected':''}" data-id="${esc(e.ID)}"><div class="env-main"><div class="env-name">${esc(e.Project)}</div><span class="badge ${statusClass(e.Status)}">${esc(e.Status)}</span></div><div class="env-branch">⎇ ${esc(e.Branch)}</div><div class="env-meta"><span>${esc(e.Subdomain)}.${esc(state.baseDomain)}</span><span>${esc(expiry(e.TTLExpiresAt))}</span><span>${esc(relativeTime(e.UpdatedAt))}</span></div></div>`).join(''):'<div class="empty">No environments match this filter.</div>';document.querySelectorAll('.environment').forEach(x=>x.onclick=()=>select(x.dataset.id))}
async function select(id){state.selected=state.envs.find(e=>e.ID===id)||null;renderList();renderDetail();loadLogs()}
function renderDetail(){const e=state.selected;if(!e){$('detail').hidden=true;$('detail-empty').hidden=false;return}$('detail-empty').hidden=true;$('detail').hidden=false;const s=String(e.Status).toLowerCase();const host=`${e.Subdomain}.${state.baseDomain}`;$('detail').innerHTML=`<div class="detail"><div class="detail-title"><div><h2>${esc(e.Project)}</h2><div class="detail-branch">⎇ ${esc(e.Branch)}</div></div><span class="badge ${statusClass(e.Status)}">${esc(e.Status)}</span></div><div class="actions"><a class="button primary" href="https://${esc(host)}" target="_blank" rel="noreferrer">Open preview ↗</a>${s==='sleeping'?'<button class="button secondary" data-action="wake">Wake</button>':s==='ready'?'<button class="button secondary" data-action="sleep">Sleep</button>':''}<button class="button danger" data-action="destroy">Destroy</button></div><div class="facts"><div class="fact"><span>Environment ID</span><b>${esc(e.ID)}</b></div><div class="fact"><span>Preview host</span><b>${esc(host)}</b></div><div class="fact"><span>Artifact</span><b>${esc(e.ArtifactRef)}</b></div><div class="fact"><span>Expires</span><b>${esc(e.TTLExpiresAt||'No expiry')}</b></div><div class="fact"><span>Created</span><b>${esc(e.CreatedAt)}</b></div><div class="fact"><span>Updated</span><b>${esc(e.UpdatedAt)}</b></div></div><div class="logs-head"><h3>Deployment logs</h3><button class="button secondary small" id="log-refresh">Refresh</button></div><pre id="logs" class="logs">Loading logs…</pre></div>`;document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));$('log-refresh').onclick=loadLogs}
async function action(kind){if(!state.selected)return;const labels={sleep:'sleep this environment',wake:'wake this environment',destroy:'destroy this environment'};if(!confirm(`Are you sure you want to ${labels[kind]}?`))return;try{const r=await api(`/environments/${encodeURIComponent(state.selected.ID)}/${kind}`,{method:'POST'});if(kind==='destroy'){$('detail-empty').hidden=false;$('detail').hidden=true;state.selected=null}else{state.selected=await r.json()}toast(`${kind[0].toUpperCase()+kind.slice(1)} requested`);await load()}catch(e){toast(e.message)}}
async function loadLogs(){if(!state.selected)return;try{const r=await api(`/environments/${encodeURIComponent(state.selected.ID)}/logs`);$('logs').textContent=await r.text()}catch(e){if($('logs'))$('logs').textContent=e.message}}
$('refresh').onclick=load;$('filter').oninput=renderList;$('settings').onclick=openToken;
$('token-form').onsubmit=e=>{e.preventDefault();const value=$('token').value.trim();if(!value)return;state.token=value;if($('remember').checked)localStorage.setItem('ramify.token',value);else localStorage.removeItem('ramify.token');$('token-dialog').close();load()};
fetch('/dashboard/config').then(r=>r.json()).then(c=>{state.baseDomain=c.base_domain;load();state.refreshTimer=setInterval(load,5000);state.logsTimer=setInterval(loadLogs,4000)});if(!state.token)setTimeout(openToken,250);
